/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Exercici1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Scanner;

public class App {
    public static String A;
    public static Boolean resp;
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int i = 3;
        while(i>=0) {
            System.out.println("Introduzca el nombre del archivo que quieres abrir: ");
            A = scanner.nextLine();
            resp = DevolucionArchivo(A);
            if(resp){

            } else {
                i--;
            }
        }
        
    }
    
    public static boolean DevolucionArchivo(String preArchivo) {
        try {
            ComprobarArchivo(preArchivo);
            return true;
        } catch (FileDoesNotExistException e) {
            System.err.println("Excepció: " + e.getMessage());
        }
        return false;
    }
    
    public static void ComprobarArchivo(String archivo) throws FileDoesNotExistException {
        File hojatexto = new File ("C:\\Users\\blu20\\Desktop\\Eric\\Programacion\\Exercici1\\app\\src\\main\\java\\com\\example\\Exercici1\\App.java\\" + archivo +".txt");
        if(hojatexto.exists()){
            System.out.println("El archivo existe");
        }else {
            throw new FileDoesNotExistException("El fitxer especificat no existeix");
        }
    }
}

class FileDoesNotExistException extends Exception {
    public FileDoesNotExistException(String mensaje) {
        super(mensaje);
    }
}

class MaxAttemptsExceededException extends Exception {
    public  MaxAttemptsExceededException (String mensaje) {
        super(mensaje);
    }
}

class EmptyFirstLineException extends Exception {
    public EmptyFirstLineException (String mensaje) {
        super(mensaje);
    }
}

class SeparatorNotFoundException extends Exception {
    public SeparatorNotFoundException (String mensaje) {
        super (mensaje);
    }
}

class InvalidFormatException extends Exception {
    public InvalidFormatException (String mensaje){
        super (mensaje);
    }
}